import jsPDF from 'jspdf';

export function downloadReportPDF(results) {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(22);
  doc.setTextColor(28, 112, 245); // primary blue
  doc.text('TriageAI CBC Analysis Report', 20, 20);

  doc.setFontSize(10);
  doc.setTextColor(150, 150, 150);
  doc.text(`Generated on: ${new Date().toLocaleString()}`, 20, 28);

  // Risk Badge
  doc.setFontSize(14);
  let riskColor = [52, 211, 153]; // Green
  if (results.overallRisk === 'HIGH') riskColor = [248, 113, 113]; // Red
  else if (results.overallRisk === 'MEDIUM') riskColor = [251, 191, 36]; // Yellow
  
  doc.setTextColor(riskColor[0], riskColor[1], riskColor[2]);
  doc.text(`OVERALL RISK: ${results.overallRisk}`, 20, 40);

  // Table Setup
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);
  doc.text('Parameter Analysis:', 20, 55);

  let startY = 65;
  doc.setFontSize(10);
  // Table headers
  doc.setFont(undefined, 'bold');
  doc.text('Parameter', 20, startY);
  doc.text('Value', 70, startY);
  doc.text('Status', 120, startY);
  doc.text('Range', 160, startY);
  
  doc.line(20, startY + 2, 190, startY + 2);
  
  doc.setFont(undefined, 'normal');
  startY += 10;
  
  results.parameters.forEach(param => {
    doc.text(param.name, 20, startY);
    doc.text(`${param.value} ${param.unit}`, 70, startY);
    
    // Color code status
    if (param.status === 'low' || param.status === 'high') {
       doc.setTextColor(248, 113, 113);
    } else {
       doc.setTextColor(52, 211, 153);
    }
    doc.text(param.status.toUpperCase(), 120, startY);
    
    doc.setTextColor(0, 0, 0);
    doc.text(param.normalRange, 160, startY);
    
    startY += 8;
  });

  // AI Explanation
  startY += 10;
  doc.setFontSize(12);
  doc.setFont(undefined, 'bold');
  doc.text('AI Clinical Analysis:', 20, startY);
  
  startY += 8;
  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');
  const splitExplanation = doc.splitTextToSize(results.aiExplanation, 170);
  doc.text(splitExplanation, 20, startY);

  // Recommendations
  startY += (splitExplanation.length * 5) + 10;
  doc.setFontSize(12);
  doc.setFont(undefined, 'bold');
  doc.text('Recommended Actions:', 20, startY);

  startY += 8;
  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');
  
  results.recommendations.forEach(rec => {
    doc.text(`• [${rec.priority.toUpperCase()}] ${rec.text}`, 20, startY);
    startY += 6;
  });

  // Footer Disclaimer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('DISCLAIMER: This report is generated by AI for demonstration purposes only.', 20, 280);
  doc.text('It is not a substitute for professional medical advice, diagnosis, or treatment.', 20, 285);

  doc.save('TriageAI_Report.pdf');
}
